name: Continuous Integration
on: 
 pull_request:
   types: [opened, synchronize, reopened]
 push:
   branches:
     - master

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
    - name: ref
      run: echo ${{ github.ref }} 
    - name: event_name
      run: echo ${{ github.event_name }} 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: install
      run: npm install
    - name: build
      run: npm run build
    - name: coverage
      run: npm run coverage
    - name: Upload coverage to Codecov  
      if: github.event_name == 'push' && endsWith(github.ref,'/master')
      uses: codecov/codecov-action@v1.0.2
      # should not need token as it is a public repo
      with:
        token: ${{secrets.CODECOV_TOKEN}}
